In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold
from sklearn.utils import resample

In [9]:
df = pd.read_csv('metodosDeValidacion.csv')
df.head()

x   y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [10]:
x = df['x'].values
y = df['y'].values

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, shuffle= False)

In [12]:
def validacionCruzada(x_train,y_train,k):
    print('\n -------------------- \n')
    print('Validacion Cruzada')
    kf = KFold(n_splits=k)
    print('\n X \n')
    for train, test in kf.split(x_train):
        print(x_train[train] ,',', x_train[test])
    print('\n Y \n')
    for train, test in kf.split(y_train):
        print(y_train[train],',', y_train[test])

validacionCruzada(x_train,y_train,3)


 -------------------- 

Validacion Cruzada

 X 

[ 5  6  7  8  9 10 11 12] , [1 2 3 4]
[ 1  2  3  4  9 10 11 12] , [5 6 7 8]
[1 2 3 4 5 6 7 8] , [ 9 10 11 12]

 Y 

[10 12 14 16 18 20 22 24] , [2 4 6 8]
[ 2  4  6  8 18 20 22 24] , [10 12 14 16]
[ 2  4  6  8 10 12 14 16] , [18 20 22 24]


In [15]:
def dejarUnoFuera(x_train,y_train):
    print('\n -------------------- \n')
    print('Leave One Out')
    loo = LeaveOneOut()
    print(loo.get_n_splits(x_train))
    print('\n X \n')
    for i, (train_index, test_index) in enumerate(loo.split(x_train)):
        print('\n',i,x_train[train_index],',', x_train[test_index])
    print('\n Y \n')
    for i, (train_index, test_index) in enumerate(loo.split(y_train)):
        print('\n',i,y_train[train_index],',', y_train[test_index])
        
        
dejarUnoFuera(x_train,y_train)


 -------------------- 

Leave One Out
12

 X 


 0 [ 2  3  4  5  6  7  8  9 10 11 12] , [1]

 1 [ 1  3  4  5  6  7  8  9 10 11 12] , [2]

 2 [ 1  2  4  5  6  7  8  9 10 11 12] , [3]

 3 [ 1  2  3  5  6  7  8  9 10 11 12] , [4]

 4 [ 1  2  3  4  6  7  8  9 10 11 12] , [5]

 5 [ 1  2  3  4  5  7  8  9 10 11 12] , [6]

 6 [ 1  2  3  4  5  6  8  9 10 11 12] , [7]

 7 [ 1  2  3  4  5  6  7  9 10 11 12] , [8]

 8 [ 1  2  3  4  5  6  7  8 10 11 12] , [9]

 9 [ 1  2  3  4  5  6  7  8  9 11 12] , [10]

 10 [ 1  2  3  4  5  6  7  8  9 10 12] , [11]

 11 [ 1  2  3  4  5  6  7  8  9 10 11] , [12]

 Y 


 0 [ 4  6  8 10 12 14 16 18 20 22 24] , [2]

 1 [ 2  6  8 10 12 14 16 18 20 22 24] , [4]

 2 [ 2  4  8 10 12 14 16 18 20 22 24] , [6]

 3 [ 2  4  6 10 12 14 16 18 20 22 24] , [8]

 4 [ 2  4  6  8 12 14 16 18 20 22 24] , [10]

 5 [ 2  4  6  8 10 14 16 18 20 22 24] , [12]

 6 [ 2  4  6  8 10 12 16 18 20 22 24] , [14]

 7 [ 2  4  6  8 10 12 14 18 20 22 24] , [16]

 8 [ 2  4  6  8 10 12 14 16 20 22 24

In [14]:
def Bootstrap(x_train,y_train,nc,m):
    print('\n -------------------- \n')
    print('Bootstrap')
    print('\n X \n')
    for _ in range(nc):
        train = resample(x_train, n_samples=m)
        test = np.array([x for x in x_train if x not in train])
        print('train',train,'test',test)
    print('\n Y \n')
    for _ in range(nc):
        train = resample(y_train, n_samples=m)
        test = np.array([x for x in y_train if x not in train])
        print('train',train,'test',test)
        
        
Bootstrap(x_train,y_train,2,5)


 -------------------- 

Bootstrap

 X 

train [ 4  6  2 10 10] test [ 1  3  5  7  8  9 11 12]
train [6 1 7 9 8] test [ 2  3  4  5 10 11 12]

 Y 

train [20 16 16  4  8] test [ 2  6 10 12 14 18 22 24]
train [10  4 10 12 24] test [ 2  6  8 14 16 18 20 22]
